### ISSUE TITLE
Revoke and Grant: Roles must be from this guild.

### ISSUE THREAD

**Issue by ghost** [the-programmers-hangout/HangoutBot#21]
**Expected behaviour:**
tph!grant userid [NameOfRole]
Role added to user
tph!revoke userid [NameOfRole]
Role removed from user

**Actual behaviour:**
tph!grant userid [NameOfRole]
Roles must be from this guild.
tph!revoke userid [NameOfRole]
Roles must be from this guild.

Role is listed in listgrantableroles and listroles.

Is this just not implemented yet? @markhc

**Comment by markhc** [comment]
It's a KUtils bug in the preview version that the bot is currently using.

I believe it's been fixed in the latest version. I will update it when I finish some cleanup that I am currently doing.
