### ISSUE TITLE
Don't know what happened here

### ISSUE THREAD

**Issue by kahveciderin** [the-programmers-hangout/HangoutBot#46]
![image](https://user-images.githubusercontent.com/17106844/106264333-93103100-6236-11eb-94ea-abf5a97e07cb.png)

**Comment by caffeinewriter** [comment]
That's one of the welcome messages! :) 

https://github.com/the-programmers-hangout/HangoutBot/blob/216670dffae468e16a4d42731dd3e20f19afba99/src/main/kotlin/me/markhc/hangoutbot/locale/Messages.kt#L43

**Comment by kahveciderin** [comment]
well they told me to report it here, my bad
